language: node_js
node_js:
  - 10
  - 12

notifications:
  email: false

before_install:
  - pnpm add -g codecov
script:
  - pnpm test
  - codecov

branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'

jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: node # pre-installed version
      script:
        - pnpm add -g semantic-release
        - semantic-release
